name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app
      
      - name: Build
        run: |
          xcodebuild -scheme SystemMonitor \
            -destination 'generic/platform=iOS' \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            SWIFT_VERSION=5.9
      
      - uses: actions/upload-artifact@v4
        with:
          name: App
          path: build/Release-iphoneos/SystemMonitor.app
